---

- name: Install Peter's Favorite Apps
  apt:  name={{ item }} state=present
  with_items:
    # - ack
    # - awesome
    # - awesome-extra
    # - cowsay
    # - compton
    # - fortunes
    - git-all
    # - haskell-stack
    - htop
    # - mpv
    # - neovim
    # - palemoon
    # - python-pip
    # - ranger
    - rxvt-unicode-256color
    - screen
    # - udevil
    - vim-gtk
    # - workrave
    # - zsh
  become: yes
  tags:
    - peter
    - users


- name: Add a User for Peter
  user: name=peter state=present shell=/usr/bin/zsh append=yes createhome=yes
        groups=cdrom,floppy,audio,dip,video,plugdev,netdev,scanner,lpadmin,sudo
        home=/home/peter password=$1$kfDS2UJI$fqsE4SoBkTSwcApC3wzBZ1
  become: yes
  tags:
    - peter
    - users

- name: Authorize Peter's SSH keys
  authorized_key: user=peter key="{{ item }}"
  with_file:
    - peter/id_rsa.pub
  become: yes
  become_user: peter
  tags:
    - peter
    - users

- name:  Make Peter's Configuration Folder
  shell: mkdir /home/peter/.config || /bin/true
  become:  yes
  become_user: peter
  tags:
    - peter
    - users

# - name:  Pull Peter's AwesomeWM Config
#   git:   repo=http://bugs.sleepanarchy.com/awesome-config.git dest=/home/peter/.config/awesome recursive=yes
#   become:  yes
#   become_user: peter
#   tags:
#     - peter
#     - users


# - name:  Pull Peter's Dotfiles
#   git:   repo=http://bugs.sleepanarchy.com/peter/peters-dotfiles.git dest=/home/peter/.dotfiles
#   become:  yes
#   become_user: peter
#   tags:
#     - peter
#     - users

# - name:  Link Peter's Dotfiles
#   shell: ./install.sh chdir=/home/peter/.dotfiles/ creates=/home/peter/.zshrc
#   become:  yes
#   become_user: peter
#   ignore_errors: yes
#   tags:
#     - peter
#     - users

# - name: Install PEP8 and PyLint
#   pip:  name={{ item }} state=present
#   with_items:
#     - pep8
#     - pylint
#   become: yes
#   tags:
#     - peter
#     - users

# - name: Install YouCompleteMe Dependencies
#   apt:  name={{ item }} state=present
#   with_items:
#     - cmake
#     - build-essential
#     - python-dev
#   become: yes
#   tags:
#     - peter
#     - users

# - name: Copy over the Hypnotoad Cow File
#   copy: src=peter/hypnotoad.cow dest=/usr/share/cowsay/cows/hypnotoad.cow
#   become:  yes
#   tags:
#     - peter
#     - users

- name:  Set Peter's Default XSession to i3
  shell: echo "[Desktop]\nSession=i3" > ~/.dmrc creates=/home/peter/.dmrc
  become:  yes
  become_user: peter
  tags:
    - peter
    - users

- name:  Create Peter's XDG User Directories
  shell: xdg-user-dirs-update
  become:  yes
  become_user: peter
  tags:
    - peter
    - users
