---

- name: Ensure Base Applications are Installed
  apt:  name={{ item }} state=present install_recommends=yes
  with_items:
    - alsa-utils
    - anacron
    - avahi-daemon
    - eject
    - firmware-linux
    - hddtemp
    - iw
    - kmod
    - libgl1-mesa-dri
    - libnss-mdns
    - p7zip-full
    - pm-utils
    - sudo
    - udisks2
    - unattended-upgrades
    - upower
    - xdg-user-dirs
    - xdg-utils
    - xorg
  become: yes
  tags: apps

# Built from `out of the top of my head`
- name: Ensure i3 and my main applications are installed
  apt:  name={{ item }} state=present install_recommends=yes
  with_items:
    - lightdm
    - i3
    - 
  become: yes
  tags:
    - apps
    - i3

# - name: Ensure Packages for Firefox-KDE Integration are Installed
#   apt:  name={{ item }} state=present
#   with_items:
#     - i3-config-gtk-style
#     - gtk3-engines-breeze
#   become: yes
#   tags:
#     - apps
#     - i3

- name: Ensure Internet Applications and Plugins are Installed
  apt:  name={{ item }} state=present
  with_items:
    - chromium
    - filezilla
    - calibre
    # - cherrytree
    - flameshot
    - geany
    - gpsbabel-gui
    - gpscorrelate
    - gpsprune
    - inkscape
    # - qlandkartegt
    - qmapshack
    - scribus
    - thunar
    - transmission
    - viking
    - xsane
    - zim
    - stack-client
    # - eid-viewer
    # - eid-mw
    # - beid-mozilla-extension
    # - beid-mozilla-webext
    # - eid-archive
  become: yes
  tags: apps

- name: Ensure LibreOffice is Installed
  apt:  name={{ item }} state=present
  with_items:
    - libreoffice
    - libreoffice-help-en-us
#    - libreoffice-kde
    - libreoffice-pdfimport
    - libreoffice-style-breeze
    # - libreoffice-style-galaxy
    - mythes-en-us
    - hunspell-en-us
    - hunspell-nl
    - hyphen-en-us
    - hyphen-nl
  become: yes
  tags: apps

# - name: Ensure Multimedia Codecs are Installed
#   apt:  name={{ item }} state=present
#   with_items:
#     - gir1.2-gst-plugins-base-1.0
#     - gstreamer1.0-fluendo-mp3
#     - gstreamer1.0-plugins-bad
#     - gstreamer1.0-plugins-good
#     - gstreamer1.0-plugins-ugly
#     - gstreamer1.0-pulseaudio
#     - libavcodec-extra
#   become: yes
#   tags: apps

- name: Ensure Miscellaneous Applications and Utilities are Installed
  apt:  name={{ item }} state=present
  with_items:
#    - tome
#    - crawl-tiles
    - gimp
    - gimp-data-extras
    - sqlite3
#    - tumbler
#    - tumbler-plugins-extra
#    - vlc
  become: yes
  tags: apps
